### ISSUE TITLE
Create pre-built wheel

### ISSUE THREAD

**Issue by filips123** [amitdev/lru-dict#23]
Please create pre-built wheels for Windows, Linux and macOS to allow easier installation of the package. You can use Travis CI or other CI for this.

You can use [wheelwright](https://github.com/explosion/wheelwright) for this.

**Comment by cool-RR** [comment]
I will also benefit from this. It's nice that there's a build on https://www.lfd.uci.edu/~gohlke/pythonlibs/ but it would be better if there was one on PyPI so we could `pip install` it.

**Comment by itssimon** [comment]
I would also benefit from this

**Comment by matusf** [comment]
Same here

**Comment by Erotemic** [comment]
This can be done very easily on github actions these days. See https://github.com/pyutils/line_profiler for a reasonable template.

**Comment by AndreMiras** [comment]
I would be happy to help with that, I've started making a PR to run tests on GitHub Actions, if it gets merged, I will follow up on auto publishing to PyPI.
https://github.com/amitdev/lru-dict/pull/37

**Comment by AndreMiras** [comment]
First one merged, follow up pull requests deals with building the wheels for different platforms and Python versions, see https://github.com/amitdev/lru-dict/pull/38
If that one gets merged, the last one is to upload to PyPI

**Comment by AndreMiras** [comment]
Last piece of the puzzle https://github.com/amitdev/lru-dict/pull/40

**Comment by AndreMiras** [comment]
Awesome, thanks for the merge @amitdev :partying_face: 
I saw you tagged a new release, I'm having my eyes on the build and will help debugging if something goes off.
If everything goes well I'll try to install the PyPI version straight away see how it went as well

**Comment by amitdev** [comment]
Thanks for making the changes! Looks like it worked.
